### ISSUE TITLE
doesn't work with terraform 0.7

### ISSUE THREAD

**Issue by eghobo** [samsung-cnct/terraform-provider-execute#2]
@maratoid: any plans to release version for terraform 0.7

**Comment by maratoid** [comment]
Hello!
Try the 0.0.3 release.

**Comment by eghobo** [comment]
@maratoid: it works like charm, thx a lot for quick response. any plans to rebuild coreosbox as well.

**Comment by maratoid** [comment]
I actually just did. The latest release should work with tf 7

**Comment by eghobo** [comment]
thx a lot, last step is brew update ;), sorry if asking too much.

**Comment by maratoid** [comment]
So, that might take a little while longer - I want to make sure I don't break any of our stuff that might still depend on older terraform.

**Comment by eghobo** [comment]
yep, but honestly brew keep only latest version (e.g. you cannot install terraform 0.6 anymore) and find previous version is always headache with brew.

**Comment by maratoid** [comment]
```
brew tap 'Samsung-AG/terraform-provider-execute'
brew install terraform-provider-execute
```

and 

```
brew tap 'Samsung-AG/terraform-provider-coreosbox'
brew install terraform-provider-coreosbox
```

**Comment by eghobo** [comment]
works great, thx a lot
