### ISSUE TITLE
doesn't work with terraform 0.8

### ISSUE THREAD

**Issue by eghobo** [samsung-cnct/terraform-provider-execute#5]
`` 
Error configuring: 1 error(s) occurred:
*Incompatible API version with plugin. Plugin version: 1, Ours: 2
``

@maratoid: do you mind rebuild/publish this plugin with  terraform 0.8 dependencies?

**Comment by coffeepac** [comment]
new release has been cut:  https://github.com/samsung-cnct/terraform-provider-execute/releases/tag/v0.0.4

going to update the brew tap now

**Comment by coffeepac** [comment]
@eghobo lemme know if this works or doesn't work for you.  If works I'll close it you (or you can).  If it doesn't work I'll fix it.

**Comment by eghobo** [comment]
@coffeepac: works like a charm, thx a lot.

**Comment by coffeepac** [comment]
@eghobo awesome, thanks for testing it out!
